version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/home/app
    ports:
      - "3000:3000"
    restart: unless-stopped
